# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PCView.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog
from tkinter import filedialog
from datetime import datetime
import time, os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow, master):
        self.MainWindow= MainWindow
        self.MainWindow.setWindowIcon(QtGui.QIcon(os.getcwd() + '/CompassX.ico'))
        self.master= master
        self.FILESELECT= ""
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CALENDARIO = QtWidgets.QCalendarWidget(self.centralwidget)
        self.CALENDARIO.setGeometry(QtCore.QRect(50, 220, 351, 231))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        self.CALENDARIO.setFont(font)
        self.CALENDARIO.setStyleSheet("QWidget#qt_calendar_navigationbar\n"
"{\n"
"    font: 75 12pt \"Century Gothic\";\n"
"    background-color: #FF6600;\n"
"    border: 1px solid #4f4f4f;\n"
"}\n"
"")
        self.CALENDARIO.setObjectName("CALENDARIO")
        self.ANP = QtWidgets.QSlider(self.centralwidget)
        self.ANP.setGeometry(QtCore.QRect(640, 230, 101, 31))
        self.ANP.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: #FF6600;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"    background: #fca972;\n"
"}")
        self.ANP.setMaximum(1)
        self.ANP.setOrientation(QtCore.Qt.Horizontal)
        self.ANP.setInvertedControls(False)
        self.ANP.setObjectName("ANP")
        self.DENTICAO = QtWidgets.QComboBox(self.centralwidget)
        self.DENTICAO.setGeometry(QtCore.QRect(50, 140, 231, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        self.DENTICAO.setFont(font)
        self.DENTICAO.setStyleSheet("")
        self.DENTICAO.setObjectName("DENTICAO")
        self.DENTICAO.addItem("")
        self.DENTICAO.addItem("")
        self.DENTICAO.addItem("")
        self.DENTICAO.addItem("")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 10, 401, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(26)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #FF6600")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(-10, -250, 1391, 1111))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap(":/Fundo/fundo.png"))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(660, 190, 71, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 260, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.POGNP = QtWidgets.QSlider(self.centralwidget)
        self.POGNP.setGeometry(QtCore.QRect(640, 300, 101, 31))
        self.POGNP.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: #FF6600;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"    background: #fca972;\n"
"}")
        self.POGNP.setMaximum(1)
        self.POGNP.setOrientation(QtCore.Qt.Horizontal)
        self.POGNP.setInvertedControls(False)
        self.POGNP.setObjectName("POGNP")
        self.GNMSP = QtWidgets.QSlider(self.centralwidget)
        self.GNMSP.setGeometry(QtCore.QRect(640, 370, 101, 31))
        self.GNMSP.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: #FF6600;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"    background: #fca972;\n"
"}")
        self.GNMSP.setMaximum(1)
        self.GNMSP.setOrientation(QtCore.Qt.Horizontal)
        self.GNMSP.setInvertedControls(False)
        self.GNMSP.setObjectName("GNMSP")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(650, 330, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.LDM = QtWidgets.QSlider(self.centralwidget)
        self.LDM.setGeometry(QtCore.QRect(640, 440, 101, 31))
        self.LDM.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: #FF6600;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"    background: #fca972;\n"
"}")
        self.LDM.setMaximum(1)
        self.LDM.setOrientation(QtCore.Qt.Horizontal)
        self.LDM.setInvertedControls(False)
        self.LDM.setObjectName("LDM")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(670, 400, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.UDM = QtWidgets.QSlider(self.centralwidget)
        self.UDM.setGeometry(QtCore.QRect(640, 510, 101, 31))
        self.UDM.setStyleSheet("QSlider::handle:horizontal {\n"
"    background: #FF6600;\n"
"}\n"
"QSlider::add-page:horizontal {\n"
"    background: white;\n"
"}\n"
"\n"
"QSlider::sub-page:horizontal{\n"
"    background: #fca972;\n"
"}")
        self.UDM.setMaximum(1)
        self.UDM.setOrientation(QtCore.Qt.Horizontal)
        self.UDM.setInvertedControls(False)
        self.UDM.setObjectName("UDM")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(670, 470, 91, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(530, 10, 251, 171))
        self.label_8.setStyleSheet("b")
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/Logo/Logo Compass.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.TXTFILE = QtWidgets.QLabel(self.centralwidget)
        self.TXTFILE.setGeometry(QtCore.QRect(60, 500, 311, 51))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(16)
        self.TXTFILE.setFont(font)
        self.TXTFILE.setStyleSheet("border: 1px solid #ff6600")
        self.TXTFILE.setObjectName("TXTFILE")
        self.BTNFILE = QtWidgets.QPushButton(self.centralwidget)
        self.BTNFILE.setGeometry(QtCore.QRect(368, 500, 121, 52))
        font = QtGui.QFont()
        font.setFamily("Century Gotic")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.BTNFILE.setFont(font)
        self.BTNFILE.setStyleSheet("background: #ff6600;\n"
"color: white;\n"
"font: 15pt \"Century Gotic\";")
        self.BTNFILE.setObjectName("BTNFILE")
        self.BTNFILE.clicked.connect(self.openFileNamesDialog)
        self.label_2.raise_()
        self.CALENDARIO.raise_()
        self.ANP.raise_()
        self.DENTICAO.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.POGNP.raise_()
        self.GNMSP.raise_()
        self.label_5.raise_()
        self.LDM.raise_()
        self.label_6.raise_()
        self.UDM.raise_()
        self.label_7.raise_()
        self.label_8.raise_()
        self.TXTFILE.raise_()
        self.BTNFILE.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
    def openFileNamesDialog(self):
        try:
                options = QFileDialog.Options()
                options |= QFileDialog.DontUseNativeDialog
                files, _ = QFileDialog.getOpenFileNames(self.MainWindow,"QFileDialog.getOpenFileNames()", "","All Files (*);;Python Files (*.py)", options=options)
                last= files[0].split("/")[len(files[0].split("/"))-1]
                if(".csv" in last):        
                        self.TXTFILE.setText(f"<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">{last}</span></p></body></html>")
                        self.FILESELECT= files[0]
                        self.handShake()
                else:
                        self.TXTFILE.setText(f"<html><head/><body><p align=\"center\"><span style=\" color:#ff0000;\">Formato Inválido</span></p></body></html>")
                        self.FILESELECT= None
        except Exception:
                pass
    def handShake(self):
        self.master.forms= {
                "A - Np": self.ANP.value(),
                "Pog - Np": self.POGNP.value(),
                "Gn MSP": self.GNMSP.value(),
                "LDM": self.LDM.value(),
                "UDM": self.UDM.value()
        }
        self.master.filepath= self.FILESELECT
        self.master.denticao= self.DENTICAO.currentText()
        datanascimento= self.CALENDARIO.selectedDate()
        dataatual= datetime.today()
        if(dataatual.month < datanascimento.month()):
                self.master.idade= dataatual.year - datanascimento.year() - 1
        elif(dataatual.month == datanascimento.month() and datanascimento.day() < dataatual.day):
                print(2)
                self.master.idade= dataatual.year - datanascimento.year() - 1
        else:
                print(4)
                self.master.idade= dataatual.year - datanascimento.year()
        self.MainWindow.close()
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "CompassX - Protocolo Compass3D - 2023 Edition"))
        self.DENTICAO.setCurrentText(_translate("MainWindow", "Selecione uma dentição"))
        self.DENTICAO.setItemText(0, _translate("MainWindow", "Selecione uma dentição"))
        self.DENTICAO.setItemText(1, _translate("MainWindow", "Decídua"))
        self.DENTICAO.setItemText(2, _translate("MainWindow", "Mista"))
        self.DENTICAO.setItemText(3, _translate("MainWindow", "Permanente"))
        self.label.setText(_translate("MainWindow", "Protocolo Compass3D"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">A - Np</span></p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Pog -Np</span></p></body></html>"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">Gn MSP</span></p></body></html>"))
        self.label_6.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">LDM</span></p></body></html>"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ffffff;\">UDM</span></p></body></html>"))
        self.TXTFILE.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" color:#ffffff;\">Selecione um arquivo</span></p></body></html>"))
        self.BTNFILE.setText(_translate("MainWindow", "Procurar"))
from Views import imagens_rc


class Execute:
        def __init__(self):
            app = QtWidgets.QApplication([])
            MainWindow = QtWidgets.QMainWindow()
            ui = Ui_MainWindow()
            ui.setupUi(MainWindow, self)
            MainWindow.show()
            app.exec_()
